# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e3b66e36a2d72d9e662befd1b4b4f9a6703cfb559ac4147e32e273987a86a5fc370a15c3d61fa824cbfe94ba56e70e387564f9b95c72e91ef1779a3c405f386

test:
  secret_key_base: de097c2c0c5def46d7bae0754bd0af3be7a328ef5cef5128691804395516ece6abb87b9baae0bb19e53fec91ca9c38a2a766f30cbc1049b5fc77323d334b91a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
